[package]
name = "flowrs-std"
version = "0.2.0"
edition = "2021"
authors = ["wuermseer.florian@gmail.com", "markus.friedrich@hm.edu"]
description = "A standard library for the flowrs library."
repository = "https://github.com/flow-rs/flowrs-std"
license = "Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/flowrs-std"
keywords = ["flow", "fbp", "wasm", "std", "flow-package"]
categories = ["data-structures", "wasm"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.72"
serde = "1.0.184"
serde_json = "1.0.104"
bincode = "1.3.3"
web-time = "0.2.0"
wasm-bindgen = "0.2.87"
tracing = "0.1"

# Optional logging & tracing, enabled via native feature
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"], optional = true }
env_logger = { version = "0.10", optional = true }

# Git version of flowrs with native feature available
flowrs = { git = "https://github.com/flow-rs/flowrs", branch = "mtMophima-exec", default-features = false }

# Native-only dependencies
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.43.0", features = ["full"] }

# WASM-safe subset of tokio
[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { version = "1.43.0", features = ["rt", "macros", "time", "sync"] }

[features]
default = ["native"]

native = [
    "tracing-subscriber",
    "env_logger",
    "flowrs/native"
]
